name: Build dev

on:
  push:
    branches:
    - dev
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      project_id: ${{ vars.PROJECT_ID_DEV }}
      tag: dev
      registry_environment: dev
      multiarch: true
      runs_on_arm: 'ubuntu-latest-arm'
    secrets:
      gcp_provider: ${{ secrets.GCP_ID_PROVIDER_DEV }}
