name: Build preprod

on:
  push:
    branches:
    - "release-[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      project_id: ${{ vars.PROJECT_ID_PREPROD }}
      tag: preprod
      registry_environment: preprod
      multiarch: true
      runs_on_arm: 'ubuntu-24.04-arm'
    secrets:
      gcp_provider: ${{ secrets.GCP_ID_PROVIDER_PREPROD }}
