name: CI/CD

on:
  push:
    branches:
    - main
    - dev
    - preprod
  workflow_dispatch:
  repository_dispatch:
    types: [restart-trigger]

jobs:
  precommit:
    uses: deepalertai/global_actions/.github/workflows/precommit.yml@main

  build:
    needs: precommit
    uses: deepalertai/global_actions/.github/workflows/build.yml@main
    with:
      project_id: ${{ vars[format('PROJECT_ID_{0}', github.ref_name)] }}
    secrets:
      gcp_provider: ${{ secrets[format('GCP_ID_PROVIDER_{0}', github.ref_name)] }}
